name: Test Build on Push
run-name: ${{ github.actor }} is running a build.
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x86
      - name: Build something
        run: |
          nmake debug=1
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: meridian_client_server
          path: "./run"