name: Test Build on Push
run-name: ${{ github.actor }} is running a build.
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x86
      - name: Build something
        run: msbuild Meridian59.sln /p:Configuration=Release|Win32 /p:Platform="Any CPU"
      - name: Upload client artifact
        uses: actions/upload-artifact@v3
        with:
          name: meridian_client
          path: "./run/localclient"
      - name: Upload server artifact
        uses: actions/upload-artifact@v3
        with:
          name: meridian_server
          path: "./run/server"
      - name: Upload utils artifact
        uses: actions/upload-artifact@v3
        with:
          name: meridian_utils
          path: "./bin"