name: Test Build on Push
run-name: ${{ github.actor }} is running a build.
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Resources
        uses: actions/checkout@v2
        with:
            lfs: true
            repository: xmycroftx/meridian_resource
            path: './m59res'
            token: ${{ secrets.checkout_resources }}
      - name: Download resources
        run: |
          cd m59res
          git lfs pull
      - name: Extract Resources
        run: 7z x ./m59res/resource_04122002_OM105.7z -om59res
      - uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x86
      - name: Build something
        run: |
          nmake debug=1
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: meridian_client_server
          path: "./run"